name: "\U0001F41B Bug report"
description: Report an issue or possible bug
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        ##  Quick Checklist
        Thank you for taking the time to file a bug report! Please fill out this form as completely as possible.

        ✅ I am using the **latest version of `astro-theme-pure`** and all plugins.
        ✅ I am using a version of Node that Astro supports (`v18.17.1` or `v20.3.0` or higher.)
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: If this issue only occurs in one browser, which browser is a problem?
      placeholder: Chrome, Firefox, Safari
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue.
          required: false
